### ISSUE TITLE
Access Denied downloading Cumulus Vagrant box

### ISSUE THREAD

**Issue by alhamdubello** [CumulusNetworks/cldemo-evpn-symmetric#7]
Hi there,

I tried to run a `vagrant up oob-mgmt-server oob-mgmt-switch` but received a return message shown below. 
`An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
The requested URL returned error: 403 Forbidden` 

I checked the s3.amazon URL which redirects to a permission denied page for (https://s3.amazonaws.com/cumulusfiles/CumulusLinux-3.7.11/cumulus-linux-3.7.11-vx-amd64-vbox.box).

Please, would appreciate, if anyone could help.

Regards

Alhamdu

**Comment by alhamdubello** [comment]
Just to add. also tested with various versions with the same result. `vagrant box add CumulusCommunity/cumulus-vx --box-version 3.7.11`.
```=> box: Adding box 'CumulusCommunity/cumulus-vx' (v3.7.11) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/CumulusCommunity/boxes/cumulus-vx/versions/3.7.11/providers/virtualbox.box
    box: Download redirected to host: s3.amazonaws.com
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 403 Forbidden```

**Comment by plumbis** [comment]
This was an error on my part. The links on Vagrant have been updated and if you try again, you shouldn't have any problems.

**Comment by alhamdubello** [comment]
All working now. Thanks for the quick response.
